steps:
  # Step 1: Generate a BUILD_TAG using the current timestamp
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_TAG=$(date +%Y%m%d-%H%M%S)
        echo $BUILD_TAG > /workspace/build_tag.txt

  # Step 2: Build Docker image with the dynamic BUILD_TAG
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_TAG=$(cat /workspace/build_tag.txt)
        docker build -t asia-south1-docker.pkg.dev/logical-hallway-412312/creatorott/manoj:$BUILD_TAG .

  # Step 3: Push Docker image to the registry with the dynamic BUILD_TAG
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_TAG=$(cat /workspace/build_tag.txt)
        docker push asia-south1-docker.pkg.dev/logical-hallway-412312/creatorott/manoj:$BUILD_TAG
        
# Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'your-cloud-run-service',
      '--image', 'jfrog.artifactory.com/<repo>/your-image:${SHORT_SHA}',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Substitutions allow easy customization of the image tag and project details.
substitutions:
  _ARTIFACTORY_REPO: "jfrog.artifactory.com/<repo>"
  _CLOUD_RUN_SERVICE: "your-cloud-run-service"
