steps:
  # Step 1: Set an environment variable for the build version using the build ID
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'export BUILD_TAG=$(date +%Y%m%d-%H%M%S)']

  # Step 2: Build Docker image with automatic build number
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/logical-hallway-412312/creatorott/manoj:$BUILD_TAG', '.']

  # Step 3: Push Docker image to Artifactory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/logical-hallway-412312/creatorott/manoj:$BUILD_TAG']
  # Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'your-cloud-run-service',
      '--image', 'jfrog.artifactory.com/<repo>/your-image:${SHORT_SHA}',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Substitutions allow easy customization of the image tag and project details.
substitutions:
  _ARTIFACTORY_REPO: "jfrog.artifactory.com/<repo>"
  _CLOUD_RUN_SERVICE: "your-cloud-run-service"
